/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.mate.Operacion;

public class App {
    public static void main(String[] args) {

        float num1 = 20;
        float num2 = 10;

        Operacion op = new Operacion(num1, num2);

        System.out.println("Prueba Funcional");
        System.out.println("Suma: " + op.sumar());
        System.out.println("Resta: " + op.restar());
        System.out.println("Multiplicación: " + op.multiplicar());
        System.out.println("División: " + op.dividir());

    }
}
