/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import org.example.mate.Operacion;

class AppTest {

    private final Operacion op = new Operacion(10, 10);

    @Test
    void testAddition() {
        assertEquals(20, op.sumar());
    }

    @Test
    void testSubtraction() {
        assertEquals(0, op.restar());
    }

    @Test
    void testMultiplication() {
        assertEquals(100, op.multiplicar());
    }

    @Test
    void testDivision() {
        assertEquals(1, op.dividir());
    }

    @Test
    void testDivisionWithError() {
        Operacion opWe = new Operacion(10, 0);
        assertThrows(ArithmeticException.class, () -> opWe.dividir());
    }
}
